"""Deterministic Execution Log and JSONL Serialization for NexusAI Agent Runtime."""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from nexusai.brain.runtime.working_memory import WorkingMemory


def compute_core_state_hash(memory: WorkingMemory) -> str:
    """Compute canonical, insertion-order invariant SHA-256 hash of WorkingMemory core state."""
    state_payload = {
        "goal": memory.goal.description,
        "step_count": len(memory.steps),
        "observation_ids": sorted([obs.id for obs in memory.observations]),
    }
    raw_bytes = json.dumps(state_payload, sort_keys=True).encode("utf-8")
    return hashlib.sha256(raw_bytes).hexdigest()[:16]


def compute_extended_state_hash(memory: WorkingMemory) -> str:
    """Compute extended SHA-256 hash including scratchpad logs and failure records for debugging."""
    state_payload = {
        "goal": memory.goal.description,
        "step_count": len(memory.steps),
        "current_step_index": memory.current_step_index,
        "observation_ids": sorted([obs.id for obs in memory.observations]),
        "scratchpad_count": len(memory.scratchpad),
        "failure_count": len(memory.failures),
    }
    raw_bytes = json.dumps(state_payload, sort_keys=True).encode("utf-8")
    return hashlib.sha256(raw_bytes).hexdigest()[:16]


# Backward-compatible alias
compute_state_hash = compute_core_state_hash


@dataclass(frozen=True)
class ExecutionEvent:
    """Immutable single-event payload representing a turn execution step for deterministic replay.

    Attributes:
        event_id: Unique event UUID string.
        session_id: Session UUID string.
        turn_index: Monotonic turn loop index integer.
        step_title: Executed step title string.
        tool_name: Executed tool name string.
        tool_arguments: Arguments map passed to tool execution.
        observation_payload: String payload generated by observation.
        observation_success: Boolean success flag.
        compaction_triggered: Boolean flag indicating context compaction trigger.
        summary_text: Summary text content generated during turn compaction.
        decision: Loop decision string (e.g. CONTINUE, REPLAN, COMPLETE, FAIL).
        timestamp: Epoch timestamp float when event occurred.
    """

    event_id: str
    session_id: str
    turn_index: int
    step_title: str
    tool_name: str
    tool_arguments: dict[str, Any] = field(default_factory=dict)
    observation_payload: str = ""
    observation_success: bool = True
    compaction_triggered: bool = False
    summary_text: str = ""
    decision: str = "CONTINUE"
    timestamp: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        """Convert ExecutionEvent to serializable dictionary."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ExecutionEvent:
        """Construct ExecutionEvent from dictionary."""
        return cls(
            event_id=data["event_id"],
            session_id=data["session_id"],
            turn_index=data["turn_index"],
            step_title=data.get("step_title", ""),
            tool_name=data.get("tool_name", ""),
            tool_arguments=data.get("tool_arguments", {}),
            observation_payload=data.get("observation_payload", ""),
            observation_success=data.get("observation_success", True),
            compaction_triggered=data.get("compaction_triggered", False),
            summary_text=data.get("summary_text", ""),
            decision=data.get("decision", "CONTINUE"),
            timestamp=data.get("timestamp", 0.0),
        )


@dataclass(frozen=True)
class ExecutionLog:
    """Immutable collection container wrapping a full turn execution stream for deterministic replay.

    Attributes:
        session_id: Session UUID string.
        goal_description: Target AgentGoal description string.
        events: Tuple of ExecutionEvent items in chronological order.
        schema_version: JSONL format schema version integer (default 1).
        expected_state_hash: Optional SHA-256 hash of expected final WorkingMemory state.
    """

    session_id: str
    goal_description: str
    events: tuple[ExecutionEvent, ...] = ()
    schema_version: int = 1
    expected_state_hash: str = ""

    def save_jsonl(self, file_path: Path | str) -> None:
        """Serialize ExecutionLog to JSONL file format with schema_version integer and state hash headers."""
        path = Path(file_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as f:
            header = {
                "type": "HEADER",
                "schema_version": self.schema_version,
                "session_id": self.session_id,
                "goal_description": self.goal_description,
                "event_count": len(self.events),
                "expected_state_hash": self.expected_state_hash,
            }
            f.write(json.dumps(header) + "\n")
            for event in self.events:
                f.write(json.dumps(event.to_dict()) + "\n")

    @classmethod
    def load_jsonl(cls, file_path: Path | str) -> ExecutionLog:
        """Deserialize ExecutionLog from JSONL file format with integer schema_version validation."""
        path = Path(file_path)
        lines = path.read_text(encoding="utf-8").splitlines()
        if not lines:
            raise ValueError(f"JSONL log file '{path}' is empty.")

        header = json.loads(lines[0])
        schema_version = int(header.get("schema_version", 1))
        session_id = header.get("session_id", "unknown-session")
        goal_description = header.get("goal_description", "")
        expected_state_hash = header.get("expected_state_hash", "")

        events: list[ExecutionEvent] = []
        for line in lines[1:]:
            if not line.strip():
                continue
            data = json.loads(line)
            if data.get("type") == "HEADER":
                continue
            events.append(ExecutionEvent.from_dict(data))

        return cls(
            session_id=session_id,
            goal_description=goal_description,
            events=tuple(events),
            schema_version=schema_version,
            expected_state_hash=expected_state_hash,
        )
