"""
NexusAI Plugin Engine public API re-exports.
"""

from __future__ import annotations

from nexusai.plugins.contracts import (
    BasePlugin,
    Capability,
    ConfigSchemaItem,
    HealthStatus,
    PluginCapability,
    PluginCapabilityType,
    PluginConfigSchema,
    PluginContext,
    PluginHealth,
    PluginManifest,
    PluginMetadata,
    PluginState,
)
from nexusai.plugins.exceptions import (
    PluginAPIVersionError,
    PluginDependencyError,
    PluginError,
    PluginLifecycleError,
    PluginLoadError,
    PluginManifestError,
    PluginPermissionError,
    PluginResolutionError,
    PluginSandboxError,
    PluginSignatureError,
    PluginValidationError,
)
from nexusai.plugins.hooks import HookHandler, HookManager, HookPayload, HookRegistry, HookType
from nexusai.plugins.runtime import (
    CapabilityNegotiator,
    DependencyResolver,
    FilesystemSource,
    LoadingPlan,
    ManifestLoader,
    MemorySource,
    PluginCandidate,
    PluginDescriptor,
    PluginDiscoveryEngine,
    PluginLifecycleManager,
    PluginLoader,
    PluginRecoveryEngine,
    PluginRegistry,
    PluginRuntime,
    PluginSandbox,
    RecoveryStrategy,
    ServiceContainer,
    ServiceLifetime,
    TaskSupervisor,
)
from nexusai.plugins.security import PermissionEnforcer, PluginSignatureVerifier, ScopedPermissions
from nexusai.plugins.telemetry import MetricRecord, MetricsInterface
from nexusai.plugins.validation import APIVersionNegotiator, PluginValidator

__all__ = [
    "APIVersionNegotiator",
    "BasePlugin",
    "Capability",
    "CapabilityNegotiator",
    "ConfigSchemaItem",
    "DependencyResolver",
    "FilesystemSource",
    "HealthStatus",
    "HookHandler",
    "HookManager",
    "HookPayload",
    "HookRegistry",
    "HookType",
    "LoadingPlan",
    "ManifestLoader",
    "MemorySource",
    "MetricRecord",
    "MetricsInterface",
    "PermissionEnforcer",
    "PluginAPIVersionError",
    "PluginCandidate",
    "PluginCapability",
    "PluginCapabilityType",
    "PluginConfigSchema",
    "PluginContext",
    "PluginDependencyError",
    "PluginDescriptor",
    "PluginDiscoveryEngine",
    "PluginError",
    "PluginHealth",
    "PluginLifecycleError",
    "PluginLifecycleManager",
    "PluginLoadError",
    "PluginLoader",
    "PluginManifest",
    "PluginManifestError",
    "PluginMetadata",
    "PluginPermissionError",
    "PluginRecoveryEngine",
    "PluginRegistry",
    "PluginResolutionError",
    "PluginRuntime",
    "PluginSandbox",
    "PluginSandboxError",
    "PluginSignatureError",
    "PluginSignatureVerifier",
    "PluginState",
    "PluginValidationError",
    "PluginValidator",
    "RecoveryStrategy",
    "ScopedPermissions",
    "ServiceContainer",
    "ServiceLifetime",
    "TaskSupervisor",
]
