"""Core Domain Models for NexusAI AI Operating System."""
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

class AgentState(str, Enum):
    """10-State Autonomous Agent Lifecycle."""
    IDLE = "IDLE"
    PLANNING = "PLANNING"
    EXECUTING = "EXECUTING"
    OBSERVING = "OBSERVING"
    EVALUATING = "EVALUATING"
    REPLANNING = "REPLANNING"
    WAITING = "WAITING"
    FINISHED = "FINISHED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class BudgetDecision(str, Enum):
    """Budget decision outcomes."""
    ALLOW = "ALLOW"
    WAIT = "WAIT"
    STOP = "STOP"
    DOWNGRADE_MODEL = "DOWNGRADE_MODEL"
    ASK_USER = "ASK_USER"

class GoalCompletionStatus(str, Enum):
    """Goal evaluation completion status."""
    YES = "YES"
    NO = "NO"
    PARTIAL = "PARTIAL"

@dataclass(frozen=True)
class Goal:
    """User goal definition."""
    prompt: str
    context_data: Dict[str, Any] = field(default_factory=dict)

@dataclass(frozen=True)
class GoalStep:
    """Step in a GoalPlan."""
    step_id: int
    title: str
    description: str
    required_capabilities: List[str] = field(default_factory=list)

@dataclass(frozen=True)
class GoalPlan:
    """High-level plan generated by TaskPlanner strategy."""
    goal: Goal
    steps: List[GoalStep] = field(default_factory=list)

@dataclass(frozen=True)
class ExecutionPlan:
    """Executable graph contract output by WorkflowCompiler."""
    plan_id: str
    goal_plan: GoalPlan
    execution_steps: List[Dict[str, Any]] = field(default_factory=list)

@dataclass(frozen=True)
class Observation:
    """Unified system-wide immutable event record."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: float = field(default_factory=time.time)
    source: str = "tool"
    tool_name: Optional[str] = None
    success: bool = True
    payload: Any = None
    severity: str = "INFO"
    artifacts: List[str] = field(default_factory=list)
    metrics: Dict[str, Any] = field(default_factory=dict)

@dataclass(frozen=True)
class EvaluationResult:
    """Structured result of reasoning evaluator."""
    goal_status: GoalCompletionStatus
    confidence: float
    failure_reason: Optional[str] = None
    repair_strategy: Optional[str] = None
    retry_recommended: bool = False

@dataclass(frozen=True)
class BudgetPolicy:
    """Resource budget constraints."""
    max_tokens: int = 100_000
    max_tool_calls: int = 50
    max_duration_seconds: float = 600.0
    max_retries: int = 3

@dataclass(frozen=True)
class AgentContext:
    """Immutable execution context updated via state reducer."""
    goal: Goal
    session_id: str
    current_state: AgentState = AgentState.IDLE
    plan: Optional[ExecutionPlan] = None
    current_step_index: int = 0
    tokens_used: int = 0
    tool_calls_count: int = 0
    retries_count: int = 0
    start_time: float = field(default_factory=time.time)

    def update(self, **kwargs: Any) -> "AgentContext":
        """Functional state reducer returning a new AgentContext snapshot."""
        current_dict = {
            "goal": self.goal,
            "session_id": self.session_id,
            "current_state": self.current_state,
            "plan": self.plan,
            "current_step_index": self.current_step_index,
            "tokens_used": self.tokens_used,
            "tool_calls_count": self.tool_calls_count,
            "retries_count": self.retries_count,
            "start_time": self.start_time,
        }
        current_dict.update(kwargs)
        return AgentContext(**current_dict)

@dataclass
class AgentSession:
    """Top-level session tracking execution history."""
    session_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    started_at: float = field(default_factory=time.time)
    current_state: AgentState = AgentState.IDLE
    history: List[Observation] = field(default_factory=list)
