"""
Abstract Base Class for NexusAI Tools.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any
from pydantic import BaseModel
from nexusai.security.guard import RiskLevel


class BaseTool(ABC):
    """Abstract Base Class enforced for all NexusAI capabilities."""

    name: str
    description: str
    risk_level: RiskLevel
    input_schema: type[BaseModel]

    @abstractmethod
    async def execute(self, *args: Any, **kwargs: Any) -> Any:
        """Execute the tool capability asynchronously.

        Args:
            *args: Positional arguments matching tool input schema.
            **kwargs: Keyword arguments matching the Pydantic input_schema.

        Returns:
            Any execution result payload.
        """
        ...

    def to_json_schema(self) -> dict[str, Any]:
        """Export tool definition to LLM function calling schema format."""
        schema = self.input_schema.model_json_schema()
        # Clean metadata fields generated by Pydantic
        schema.pop("title", None)
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": schema,
            },
        }
